name: face_recognition
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/yolov8n_int8.tflite
    - assets/model/yolov8_labels.txt
